### ISSUE TITLE
Path to Stage 4

### ISSUE THREAD

**Issue by caridy** [caridy/proposal-realms#4]
## Stage 4

 * [ ] committee approval
 * [ ] implement in two browsers
 * [ ] significant in-the-field experience
 * [ ] merge test262 tests
 * [ ] write test262 tests

## Stage 3

 * [ ] committee approval
 * [ ] spec editor signoff
 * [ ] spec reviewer signoff
 * [ ] receive implementor feedback
 * [ ] flesh out naming research

## Stage 2

 * [ ] receive developer feedback
 * [ ] committee approval
 * [ ] spec text written
 * [ ] spec reviewers selected

## Stage 1

 * [ ] presentation by @dherman

**Comment by koba04** [comment]
This spec reached stage2. Have the todos in stage2 been done?

**Comment by caridy** [comment]
@koba04 yes, but we are still looking for formal reviewers, probably will select them in the next meeting in July.

**Comment by caridy** [comment]
Update: Yesterday, an update was presented to the committee (https://github.com/tc39/proposal-realms#presentations) with overall good feedback. Reviewers were selected, and with that, we are gearing toward attempting to get to stage 3 in the upcoming meetings.

**Comment by leobalter** [comment]
I added some updates with the current patch proposed for WebKit and the html integration bits.

**Comment by evisong** [comment]
> * [ ]  [WebKit (WIP)](https://bugs.webkit.org/show_bug.cgi?id=230602) (temporarily removed)

I'm sorry to interrupt, but do you happen to have any tickets, release notes or changelogs explaining why ShadowRealms are implemented by WebKit but then removed? Thanks.

**Comment by leobalter** [comment]
TC39 agreed to hold browser release until the HTML integration is finished. That work is going slower than expected due to financial/sponsor reasons. I'd love to continue this, but I'm still working on making the resources available.
